from .pdf import PDF


def generate_basic_pdf(league_df, player_name, main_pos, plot, line_plot, bar_plot):
    """
    Function that generates and returns a pdf based on the data that it receives as parameters
    :param league_df: the dataframe obtained from the league excel file through Pandas 
    :param player_name: the player's name obtained from the frontend
    :param main_pos: the player's main position within the team 
    :param plot: a plot that has been generated by the graph_generator and needs be
    displayed onto the pdf.
    :param line_plot: a line plot that has been generated by the graph_generator and needs be 
    displayed onto the pdf.
    :param bar_plot: a bar plot that has been generated by the graph_generator and needs be 
    displayed onto the pdf.
    :return: the generated pdf as a stream output
    """
    pdf = PDF()

    pdf.set_info(player_name, league_df, main_pos)

    pdf.alias_nb_pages()
    pdf.set_font('Arial', '', 12)
    pdf.set_draw_color(250, 51, 10)
    pdf.set_fill_color(255, 230, 230)
    pdf.set_title(player_name)
    pdf.add_page()

    pdf.print_title()
    pdf.print_basic_player_info()
    pdf.print_chapter('Radar Chart', 'This graph showcases general player statistics.')
    pdf.print_plot(plot)
    pdf.print_chapter('Line Plots', 'These plots showcase player statistics over time.')
    pdf.print_plot(line_plot)
    pdf.print_chapter('Bar Plots', 'These plots showcase player statistics compared to those of players in the same position within the league.')
    pdf.print_plot(bar_plot)
    return pdf.output(dest='S')
